# Generated by Django 3.0.5 on 2020-08-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('account_status', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('acquired', 'ACQUIRED')], max_length=200, null=True)),
                ('industry_status', models.CharField(choices=[('IT', 'IT AND SERVICES'), ('Services', 'SERVICES'), ('others', 'OTHERS')], max_length=200, null=True)),
                ('Account_owner', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('acquired', 'ACQUIRED')], max_length=200, null=True)),
                ('CIDN', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbl_account_info')),
            ],
        ),
    ]
